<?php

/**
 * Implements hook_init().
 */
function bigslide_init() {
  drupal_add_js("jQuery(document).ready(function () {
    jQuery('.menu-link').bigSlide({
      menu: '#block-menu-block-1',
      push: '.bigslide-push',
      easyClose: true
    });
  });", "inline");
}

/**
 * Implements hook_preprocess_HOOK().
 */
function bigslide_preprocess_html(&$variables) {
  $variables['classes_array'][] = 'bigslide-push';
}
